[package]
org = "chuhaashanan"
name = "gsheet_new_issues"
version= "0.1.0"

[build-options]
observability-included=true

[[dependency]]
org = "ballerinax"
name = "googleapis_sheets"
version = "0.99.3"


[[dependency]]
org = "ballerinax"
name = "github"
version = "0.99.8"